// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mjerbeyhmfstcuuzjedi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1qZXJiZXlobWZzdGN1dXpqZWRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYyNDIxOTksImV4cCI6MjA1MTgxODE5OX0.jjHl86QfUqxNZw0kUp6TnrUWeA6_08J6-nI2c08xehA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);